version: "3.6"

services:
  enode:
    image: ghcr.io/machinefi/enode:latest
    depends_on:
      - "postgres"
    container_name: w3bstream-enode
    platform: linux/x86_64
    restart: always
    ports:
      - "9000:9000"
    environment:
      DIDAUTH_SERVER_ENDPOINT: "didkit:9999"
      BOOTNODE_MULTIADDR: "/dns4/bootnode-0.testnet.iotex.one/tcp/4689/ipfs/12D3KooWFnaTYuLo8Mkbm3wzaWHtUuaxBRe24Uiopu15Wr5EhD3o"
      IOTEX_CHAINID: 2
      HTTP_SERVICE_ENDPOINT: ":9000"
      DATABASE_DSN: postgres://test_user:test_passwd@postgres:5432/test?sslmode=disable
      CHAIN_ENDPOINT: "https://babel-api.testnet.iotex.io"
      PROJECT_CONTRACT_ADDRESS: "0x184C72E39a642058CCBc369485c7fd614B40a03d"
      PROJECT_FILE_DIRECTORY: "/data/test/project"
    volumes:
      - .:/data

  znode:
    image: ghcr.io/machinefi/znode:latest
    depends_on:
      - "risc0"
      - "halo2"
      - "zkwasm"
      - "postgres"
    container_name: w3bstream-znode
    platform: linux/x86_64
    restart: always
    environment:
      RISC0_SERVER_ENDPOINT: "risc0:4001"
      HALO2_SERVER_ENDPOINT: "halo2:4001"
      ZKWASM_SERVER_ENDPOINT: "zkwasm:4001"
      PROJECT_FILE_DIRECTORY: "/data/test/project"
      CHAIN_ENDPOINT: "https://babel-api.testnet.iotex.io"
      CHAIN_CONFIG: '[{"chainID":4690,"name":"iotex-testnet","endpoint":"https://babel-api.testnet.iotex.io"},{"name":"solana-testnet","endpoint":"https://api.testnet.solana.com"}]'
      PROJECT_CONTRACT_ADDRESS: "0x184C72E39a642058CCBc369485c7fd614B40a03d"
      OPERATOR_PRIVATE_KEY: ${PRIVATE_KEY:-}
      OPERATOR_PRIVATE_KEY_ED25519: ${PRIVATE_KEY_ED25519:-}
      DATABASE_DSN: postgres://test_user:test_passwd@postgres:5432/test?sslmode=disable
      BOOTNODE_MULTIADDR: "/dns4/bootnode-0.testnet.iotex.one/tcp/4689/ipfs/12D3KooWFnaTYuLo8Mkbm3wzaWHtUuaxBRe24Uiopu15Wr5EhD3o"
      IOTEX_CHAINID: 2
    volumes:
      - .:/data

  halo2:
    image: iotexdev/halo2-server:0.0.5
    container_name: halo2-service
    platform: linux/x86_64
    restart: always

  zkwasm:
    image: iotexdev/zkwasmserver:v0.0.3
    container_name: zkwasm-service
    platform: linux/x86_64
    restart: always

  risc0:
    image: iotexdev/risc0server:v0.8.1.rc4
    depends_on:
      - "postgres"
    container_name: risc0-service
    platform: linux/x86_64
    restart: always
    environment:
      DATABASE_URL: postgres://test_user:test_passwd@postgres:5432/test?sslmode=disable
      BONSAI_KEY: "${BONSAI_KEY:-}"

  postgres:
    image: postgres:14
    container_name: w3bstream-node-postgres
    restart: always
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_passwd
      POSTGRES_DB: test
    volumes:
      - ./postgres:/var/lib/postgresql/data

  didkit:
    image: ghcr.io/spruceid/didkit-http:latest
    platform: linux/amd64
    container_name: didkit-http
    restart: always
    environment:
      DIDKIT_HTTP_HTTP_PORT: 9999
      DIDKIT_HTTP_HTTP_ADDRESS: '[0,0,0,0]'
      DIDKIT_HTTP_HTTP_BODYSIZELIMIT: 2097152
      DIDKIT_HTTP_ISSUER_KEYS: '[{"kty":"OKP","crv":"Ed25519","x":"THRnf4Zj7gh93XTnII8G0tQIoYb4IbkoTqcy5TNKJlg","d":"es8N8nmdU9o5wWdCEMc2xKCigN1LKc6xro1efDy7Y7M"}, {"kty":"OKP","crv":"Ed25519","x":"STSryIxBN3pyC5YQ5GnjlMmILUWcb5M0_sHpqxxmsog","d":"BiKwVOhhI-fcMMjfcxo2AdB3ygamMmgcMzjaOUl7O6s"}]'
