version: "3.6"

services:
  w3bsequencer:
    image: ghcr.io/machinefi/sequencer:latest
    depends_on:
      - "postgres"
    container_name: w3bstream-sequencer
    platform: linux/x86_64
    restart: always
    ports:
      - "9000:9000"
    environment:
      GRPC_SERVICE_ENDPOINT: ":9001"
      HTTP_SERVICE_ENDPOINT: ":9000"
      DATABASE_DSN: postgres://test_user:test_passwd@postgres:5432/test?sslmode=disable

  w3bnode:
    image: ghcr.io/machinefi/node:latest
    depends_on:
      - "risc0"
      - "halo2"
      - "postgres"
      - "w3bsequencer"
    container_name: w3bstream-node
    platform: linux/x86_64
    restart: always
    environment:
      RISC0_SERVER_ENDPOINT: "risc0:4001"
      HALO2_SERVER_ENDPOINT: "halo2:4001"
      ZKWASM_SERVER_ENDPOINT: "zkwasm:4001"
      P2P_MULTIADDR: "/ip4/0.0.0.0/tcp/10001"
      PROJECT_FILE_DIRECTORY: "/data/test/project"
      CHAIN_ENDPOINT: "https://babel-api.testnet.iotex.io"
      PROJECT_CONTRACT_ADDRESS: "0x4F7e678B0203e0444E17512108dba4B08B39512e"
      OPERATOR_PRIVATE_KEY: ${PRIVATE_KEY:-}
      DATABASE_DSN: postgres://test_user:test_passwd@postgres:5432/test?sslmode=disable
    volumes:
      - .:/data

  halo2:
    image: iotexdev/halo2-server:0.0.5
    container_name: halo2-service
    platform: linux/x86_64
    restart: always

  zkwasm:
    image: iotexdev/zkwasmserver:v0.0.2
    container_name: zkwasm-service
    platform: linux/x86_64
    restart: always

  risc0:
    image: iotexdev/risc0server:v0.8.1.rc4
    depends_on:
      - "postgres"
    container_name: risc0-service
    platform: linux/x86_64
    restart: always
    environment:
      DATABASE_URL: postgres://test_user:test_passwd@postgres:5432/test?sslmode=disable
      BONSAI_KEY: "${BONSAI_KEY:-}"

  postgres:
    image: postgres:14
    container_name: w3bstream-node-postgres
    restart: always
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_passwd
      POSTGRES_DB: test
    volumes:
      - ./postgres:/var/lib/postgresql/data

