version: "3.6"

services:
  http-plugin:
    image: ghcr.io/machinefi/http-plugin:v0.7.0
    depends_on:
      - "postgres"
      - "enode"
    container_name: w3bstream-http-plugin
    platform: linux/x86_64
    restart: always
    ports:
      - "9000:9000"
    command: [ "-enodeAddress", "enode:9001", "-databaseDSN", "postgres://test_user:test_passwd@postgres:5432/test?sslmode=disable" ]

  enode:
    image: ghcr.io/machinefi/enode:v0.7.0
    depends_on:
      - "postgres"
    container_name: w3bstream-enode
    platform: linux/x86_64
    restart: always
    ports:
      - "9001:9001"
    environment:
      ENODE_ENV: PROD
      OPERATOR_PRIVATE_KEY: ${PRIVATE_KEY:-}
      OPERATOR_PRIVATE_KEY_ED25519: ${PRIVATE_KEY_ED25519:-}

  znode:
    image: ghcr.io/machinefi/znode:v0.7.0
    depends_on:
      - "risc0"
      - "halo2"
      - "zkwasm"
      - "wasm"
      - "postgres"
    container_name: w3bstream-znode
    platform: linux/x86_64
    restart: always
    environment:
      ZNODE_ENV: PROD

  halo2:
    image: iotexdev/halo2-server:0.0.5
    container_name: halo2-service
    platform: linux/x86_64
    restart: always

  zkwasm:
    image: iotexdev/zkwasmserver:v0.0.3
    container_name: zkwasm-service
    platform: linux/x86_64
    restart: always

  risc0:
    image: wangweixiaohao2944/risc0server:v1.0.0.rc3
    depends_on:
      - "postgres"
    container_name: risc0-service
    platform: linux/x86_64
    restart: always
    environment:
      DATABASE_URL: postgres://test_user:test_passwd@postgres:5432/test?sslmode=disable
      BONSAI_URL: https://api.bonsai.xyz
      BONSAI_KEY: "${BONSAI_KEY:-}"

  wasm:
    image: wangweixiaohao2944/wasmserver:v0.0.1.rc0
    container_name: wasm-service
    platform: linux/x86_64
    restart: always

  postgres:
    image: postgres:14
    container_name: w3bstream-node-postgres
    restart: always
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_passwd
      POSTGRES_DB: test
    volumes:
      - ./postgres:/var/lib/postgresql/data

  didkit:
    image: ghcr.io/spruceid/didkit-http:latest
    platform: linux/amd64
    container_name: didkit-http
    restart: always
    environment:
      DIDKIT_HTTP_HTTP_PORT: 9999
      DIDKIT_HTTP_HTTP_ADDRESS: '[0,0,0,0]'
      DIDKIT_HTTP_HTTP_BODYSIZELIMIT: 2097152
      DIDKIT_HTTP_ISSUER_KEYS: '[{"kty":"OKP","crv":"Ed25519","x":"THRnf4Zj7gh93XTnII8G0tQIoYb4IbkoTqcy5TNKJlg","d":"es8N8nmdU9o5wWdCEMc2xKCigN1LKc6xro1efDy7Y7M"}, {"kty":"OKP","crv":"Ed25519","x":"STSryIxBN3pyC5YQ5GnjlMmILUWcb5M0_sHpqxxmsog","d":"BiKwVOhhI-fcMMjfcxo2AdB3ygamMmgcMzjaOUl7O6s"}]'
