version: "3.6"

services:
  w3bnode:
    image: ghcr.io/machinefi/sprout:latest
    depends_on:
      - "risc0"
      - "postgres"
    container_name: w3bstream-node
    platform: linux/x86_64    
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      ENDPOINT: ":${PORT}"
      RISC0_SERVER_ENDPOINT: "risc0:4001"
      HALO2_SERVER_ENDPOINT: "halo2:4001"
      PROJECT_CONFIG_FILE: "${PROJECT_CONFIG_FILE}"
      CHAIN_ENDPOINT: "https://babel-api.testnet.iotex.io"
      OPERATOR_PRIVATE_KEY: "${OPERATOR_PRIVATE_KEY}"
    volumes:
      - .:/data

  halo2:
    image: iotexdev/halo2-server:0.0.1
    container_name: halo2-service
    restart: always

  risc0:
    image: iotexdev/risc0server:v0.8.stark
    depends_on:
      - "postgres"
    container_name: risc0-service
    platform: linux/x86_64    
    restart: always
    environment:
      DATABASE_URL: postgres://test_user:test_passwd@postgres:5432/test?sslmode=disable
  
  postgres:
    image: postgres:14
    container_name: w3bstream-node-postgres
    restart: always
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_passwd
      POSTGRES_DB: test
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
    # for manual create db table, will become auto in feature
      - "9001:5432"
